[package]
name = "lix_rs_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
lix_engine = { path = "../engine" }
async-trait = "0.1"
rusqlite = { version = "0.32", features = ["bundled"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
