[workspace]
resolver = "2"
members = [
  "packages/engine",
  "packages/js-sdk",
  "packages/text-plugin",
  "packages/rs-sdk",
  "packages/plugin-md-v2",
  "packages/plugin-binary",
]
exclude = ["packages/plugin-json-v2"]
