[package]
name = "lix_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
postgresql_embedded = { version = "0.20", features = ["tokio"] }
sqlx = { version = "0.8", features = [
  "sqlite",
  "postgres",
  "runtime-tokio-rustls",
] }
tokio = { version = "1", features = ["rt", "macros", "sync"] }

[dev-dependencies]
paste = "1"
