[package]
name = "lix_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
sqlparser = "0.60.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
postgresql_embedded = { version = "0.20", features = ["tokio"] }
paste = "1"
sqlx = { version = "0.8", features = ["sqlite", "postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["rt", "macros", "sync"] }
