[package]
name = "lix_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
cel = { version = "0.12.0", features = ["json"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "wasmbind"] }
sqlparser = { version = "0.60.0", features = ["visitor"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonschema = { version = "0.17", default-features = false }
uuid = { version = "1", features = ["v7", "std", "js"] }
unicode-normalization = "0.1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }

[dev-dependencies]
criterion = "0.8.2"
postgresql_embedded = { version = "0.20", features = ["tokio"] }
paste = "1"
sqlx = { version = "0.8", features = ["sqlite", "postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["rt", "macros", "sync"] }
wasmtime = { version = "30", features = ["component-model"] }
wasmtime-wasi = "30"

[[bench]]
name = "lix_state"
harness = false
